#!/bin/bash
#

clear
######################config####################
MESSAGE="<<<messagetext>>>"   #messagetext der versendet wird
UIN="1"                                       #startUIN default
MICQ="/home/alex/.micq/scripting"             #micq user verzeichnis
COUNTER="0"
USER=50                                      #nach wieviel usern eine pause machen? micq schmiert sonst ab
USERONE=1000
SLEEP=10                                      #wartezeit nach der $USER anzahl
###############################################

if [ "$1" = "" ];then
echo "usage: $0 -h"
exit
fi
if [ "$1" = "-f" ];then
 if [ "$3" = "" ];then
    echo "icq flooding"
    echo "usage: $0 -f <startUIN> <endUIN> "
    exit
 fi

UIN="$2"
while [ $UIN -le $3 ]
 do
  echo "msg $UIN $MESSAGE" > $MICQ
  echo -e "MSG $COUNTER an $UIN senden....  [\033[1;32mOK\033[0m]"
  UIN="$[$UIN +1]"
  COUNTER="$[$COUNTER +1]"
  SLEEP=$[$RANDOM % 15 + 1]
  echo "$SLEEP sekunden warten"
  sleep $SLEEP
   if [ "$COUNTER" = "$USER" ];then
    echo "60 sekunden warten"
    sleep 60
    USER=$[$USER +100]
   fi



done



echo "$COUNTER messages versendet"
exit
elif [ "$1" = "-s" ];then
  if [ "$2" = "" ];then
   echo "usage:$0 -s <UIN>"
   exit
  fi  
 UIN="$2"
 echo "msg $UIN $MESSAGE" > $MICQ
 echo -e "MSG an $UIN senden....  [\033[1;32mOK\033[0m]"
 exit
fi



if [ "$1" = "-h" ];then
  echo "$0 -f <startUIN> <endUIN>    #sendet eine nachricht von der startUIN bis zur endUIN"
  echo "$0 -s <UIN>                  #sendet eine nachricht an diese eine UIN"
  echo "$0 -r <UIN>  <whg>           #sendet viele nachrichten an diese eine UIN"
  echo "$0 -a <startUIN> <endUIN>    #addet alle nummern in der range"
  echo "$0 -a <file>                 #schickt eine nachricht und holt die liste aus einer datei"
  
exit

fi

if [ "$1" = "-a" ];then
  if [ "$3" = "" ];then
  echo "fuegt alle nummer einer range in dein icq ein"
  echo "usage:$0 -a <startUIN> <endUIN>"
  exit
  fi
  
UIN="$2"
EXPR=`expr $3 - $2`

#if [ "$EXPR" > = "$USERONE" ];then
# echo "$EXPR user?"
# echo "bitte keine range ueber 1000 user angeben sonst schmiert micq ab"
# exit
# fi
echo -n "$EXPR user werden geaddet"
echo
while [ $UIN -le $3 ]
 do
  COUNTER="$[$COUNTER +1]"
  echo "add $UIN $UIN" > $MICQ
  echo "[add $UIN OK-$COUNTER-$USER]    "
  UIN="$[$UIN +1]"


  if [ "$COUNTER" = "$USER" ];then
   echo "$SLEEP sekunden warten"
   sleep $SLEEP
   USER=$[$USER +100]
  fi
  echo "save" > $MICQ
echo "$UIN geaddet" >>.icqfun.log  
done
  echo -n "$EXPR user geaddet"
  echo



exit
fi
